- name: Install extra pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - boto
    - six
    - markupsafe
  tags: amazon

- name: Install setuptools at latest version
  pip:
    name: setuptools
    version: 11.3
  tags: amazon

- name: Create utils path
  file:
    path: "{{ utils_path }}"
    owner: "{{ utils_user }}"
    group: "{{ utils_group }}"
    state: directory
    mode: 0750
    recurse: true
  tags: amazon

- name: Copy start & stop playbook into utils
  template:
    src: start_stop.yml.j2
    dest: "{{ utils_path }}/start_stop.yml"
    owner: "{{ utils_user }}"
    group: "{{ utils_group }}"
    mode: 0640
  when: start_stop_list is defined
  tags: amazon

- include: s3_lifecycle.yml
  when: lifecycle_policies is defined
  tags:
    - amazon
    - lifecycle_policies
